controller_frequency: 4.0
TrajectoryPlannerROS:

  holonomic_robot: false
  #max_vel_theta 0.9
  #acc_lim_theta 1.5
  #min_vel -0.3
  #oscillation_timeout 0.1
  max_vel_x: 0.3
  escape_vel: -0.1
  occdist_scale: 0.01
  pdist_scale: 1.0
  gdist_scale: 0.35
  #heading_lookahead 0.5
  #meter_scoring true
  #dwa true
  #heading_scoring true
  controller_frequency: 4.0
