local_costmap:
   global_frame: odom
   #global_frame odom
   robot_base_frame: robot_footprint
   update_frequency: 4.0
   publish_frequency: 4.0
   width: 6.0 #20
   height: 6.0 #20
   resolution: 0.05
   static_map: false
   rolling_window: true 
